using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace PL.Order
{
    /// <summary>
    /// this window is for customer to view all its orders.
    /// order list is generated by email account as key.
    /// Interaction logic for OrderListWindow.xaml
    /// </summary>
    public partial class OrderListWindow : Window
    {
        BlApi.IBL Bl;
        public ObservableCollection<BO.OrderForList> CustomerOrders { get; set; }
        public OrderListWindow(BlApi.IBL bl, string Email)
        {
            CustomerOrders = new ObservableCollection<BO.OrderForList>(bl.Order.GetAll(delegate (DO.Order? p) { return p?.CustomerEmail == Email; }));
            InitializeComponent();
            Bl = bl;
        }
    }
}
